version: "3"
services:
  cqhttp:
    image: richardchien/cqhttp:4.12.3
    container_name: cqhttp
    ports:
      - "9000:9000"
    environment:
      - COOLQ_ACCOUNT=1553281097
      - CQHTTP_SERVE_DATA_FILES=true
      - CQHTTP_WS_REVERSE_API_URL=ws://coolqbot:8080/ws/api/
      - CQHTTP_WS_REVERSE_EVENT_URL=ws://coolqbot:8080/ws/event/
      - CQHTTP_USE_WS_REVERSE=true
      - CQHTTP_SHOW_LOG_CONSOLE=false
    volumes:
      - ./coolq:/home/user/coolq

  coolqbot:
    build: .
    container_name: coolqbot
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - cqhttp
